services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: linkazo_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/linkazo_development
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        bundle install &&
        rm -f tmp/pids/server.pid &&
        bin/rails db:prepare &&
        bin/dev
      "
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
